#######################################################################
# Server Configs
#######################################################################
server:
  host: "localhost"
  port: 8090
  maxStartupTime: 10
  isWiretapping: true
  isSecure: false
  sslCertificate: secrets/server/certificate.cert
  privateKey: secrets/server/private-pkcs8.key

#######################################################################
#  Generator Configs
#######################################################################
generator:
  type: serial

#######################################################################
#  api Configs
#######################################################################
#{include}: app_routes_v5.yaml
#{include}: app_routes_v6.yaml

#######################################################################
# Client Configs
#######################################################################
#isSecure: false
#clientSslCertificate: secrets/client/certificate.cert
#clientPrivateKey: secrets/client/private-pkcs8.key

